export const INDIAN_STATES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
]

export const CROPS = [
  'Rice',
  'Wheat',
  'Maize',
  'Cotton',
  'Sugarcane',
  'Soybean',
  'Groundnut',
  'Millets',
  'Pulses',
  'Potato',
]

export const SEASONS = ['Kharif', 'Rabi', 'Zaid']

/** Match backend `SOIL_TYPES` / crop RF encoder */
export const SOIL_TYPES = [
  'alluvial',
  'black',
  'red',
  'laterite',
  'mountain',
  'arid',
  'unknown',
]

/** Normalized keys for speech / map matching */
export const STATE_ALIASES = {
  maharashtra: 'Maharashtra',
  karnataka: 'Karnataka',
  punjab: 'Punjab',
  'uttar pradesh': 'Uttar Pradesh',
  'tamil nadu': 'Tamil Nadu',
  'west bengal': 'West Bengal',
  gujarat: 'Gujarat',
  rajasthan: 'Rajasthan',
  'madhya pradesh': 'Madhya Pradesh',
  bihar: 'Bihar',
  odisha: 'Odisha',
  orissa: 'Odisha',
  telangana: 'Telangana',
  assam: 'Assam',
  haryana: 'Haryana',
  kerala: 'Kerala',
  pondicherry: 'Puducherry',
  puducherry: 'Puducherry',
  'jammu and kashmir': 'Jammu and Kashmir',
  ladakh: 'Ladakh',
  laddak: 'Ladakh',
  chandigarh: 'Chandigarh',
  lakshadweep: 'Lakshadweep',
  'andaman and nicobar': 'Andaman and Nicobar Islands',
  'dadra and nagar haveli': 'Dadra and Nagar Haveli and Daman and Diu',
  'daman and diu': 'Dadra and Nagar Haveli and Daman and Diu',
  uttaranchal: 'Uttarakhand',
}

export const CROP_ALIASES = {
  rice: 'Rice',
  wheat: 'Wheat',
  maize: 'Maize',
  cotton: 'Cotton',
  sugarcane: 'Sugarcane',
  soybean: 'Soybean',
  groundnut: 'Groundnut',
  millets: 'Millets',
  pulses: 'Pulses',
  potato: 'Potato',
}

export const SEASON_ALIASES = {
  kharif: 'Kharif',
  rabi: 'Rabi',
  zaid: 'Zaid',
}
